name: CI

on:
    push:
        branches: [main]
    pull_request:

permissions:
    contents: read

env:
    NEXT_TELEMETRY_DISABLED: 1
    NODE_OPTIONS: --max_old_space_size=4096

jobs:
    build:
        name: Typecheck, Build, Docker image
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: npm

            - name: Install dependencies
              run: npm ci

            - name: Generate Drizzle
              run: npm run db:generate

            - name: Typecheck
              run: npx tsc -p .

            - name: Build Next.js
              run: npm run build

            - name: Upload Next build
              uses: actions/upload-artifact@v4
              with:
                  name: next-build
                  path: |
                      .next
                      package.json
                      package-lock.json

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Docker build (load to local)
              run: |
                  IMAGE_TAG="${{ github.sha }}"
                  docker buildx build \
                    --load \
                    --file Dockerfile \
                    --tag rjks-erp:${IMAGE_TAG} \
                    .
                  echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

            - name: Save image as tar
              run: |
                  docker save rjks-erp:${IMAGE_TAG} -o next-app-image-${IMAGE_TAG}.tar

            - name: Upload Docker image artifact
              uses: actions/upload-artifact@v4
              with:
                  name: docker-image
                  path: next-app-image-${{ env.IMAGE_TAG }}.tar
